export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'


export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'


export const LOGOUT_USER_BEGIN = 'LOGOUT_USER_BEGIN'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'


export const BLOG_CATEGORY_BEGIN = 'BLOG_CATEGORY_BEGIN'
export const BLOG_CATEGORY_SUCCESS = 'BLOG_CATEGORY_SUCCESS'
export const BLOG_CATEGORY_ERROR = 'BLOG_CATEGORY_ERROR'

export const ALL_POST_BEGIN = 'ALL_POST_BEGIN'
export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_ERROR = 'ALL_POST_ERROR'

export const BLOG_POST_BEGIN = 'BLOG_POST_BEGIN'
export const BLOG_POST_SUCCESS = 'BLOG_POST_SUCCESS'
export const BLOG_POST_ERROR = 'BLOG_POST_ERROR'

export const BLOG_COMMENT_BEGIN = 'BLOG_COMMENT_BEGIN'
export const BLOG_COMMENT_SUCCESS = 'BLOG_COMMENT_SUCCESS'
export const BLOG_COMMENT_ERROR = 'BLOG_COMMENT_ERROR'

export const CATEGORY_TABS_BEGIN = 'CATEGORY_TABS_BEGIN'
export const CATEGORY_TABS_SUCCESS = 'CATEGORY_TABS_SUCCESS'
export const CATEGORY_TABS_ERROR = 'CATEGORY_TABS_ERROR'


